---
- name: Instalar Kubernetes 1.28 en Ubuntu
  hosts: all
  become: yes
  vars:
    kubernetes_version: 1.28
  tasks:
    - name: Cargar el módulo br_netfilter
      modprobe:
        name:
          - br_netfilter
          - overlay
        state: present
      become: yes

    - name: Parámetros de sysctl necesarios
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
      become: yes
    - name:
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
      become: yes
    - name:
      sysctl: 
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
      become: yes

    - name: Instalar los paquetes necesarios
      apt:
        name: ['apt-transport-https', 'ca-cerftificates', 'curl']
        state: present
      become: yes

    - name: Crear directorio para almacenar las claves
      file:
        path: /etc/apt/keyrings
        state: directory
    - name: Obtener y almacenar claves públicas
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        state: present
      become: yes

    - name: Ubicar paquetes de Kubernetes
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      become: yes

    - name: Instalar kubelet, kubeadm y kubectl y actualizar caché
      apt:
        name: 
          - 'kubelet=1.28.2-00'
          - 'kubeadm=1.28.2-00'
          - 'kubectl=1.28.2-00'
        state: present
        update_cache: yes
        become: yes